import type {
  EnablerProfile,
  Review,
  Insight,
  User,
  StartupProfile,
  Organization,
  Booking,
  CreditTransaction,
} from "@/types";

export const ENABLERS: (EnablerProfile & { fullName: string; avatarInitial: string; avatarUrl: string })[] = [
  {
    userId: "e1",
    fullName: "Sarah Chen",
    avatarInitial: "SC",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face",
    university: "Stanford GSB",
    degreeType: "MBA '24",
    specialties: ["B2B SaaS", "Go-to-Market", "Partnerships"],
    location: "San Francisco, CA",
    bio: "전 Google Cloud 파트너십 매니저. Stanford GSB에서 B2B SaaS GTM 전략을 전공했으며, 15개 이상의 한국 스타트업이 미국 시장에 진출하도록 도왔습니다.",
    creditRate: 2,
    enablerScore: 94,
    badgeLevel: "top_rated",
    status: "approved",
    sessionCount: 87,
    rating: 4.9,
    reRequestRate: 78,
    availability: {},
  },
  {
    userId: "e2",
    fullName: "James Park",
    avatarInitial: "JP",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    university: "Wharton",
    degreeType: "MBA '23",
    specialties: ["Fintech", "Fundraising", "IR Strategy"],
    location: "New York, NY",
    bio: "Wharton MBA 졸업 후 NYC 핀테크 씬에서 활동 중. Goldman Sachs 출신으로 IR 전략과 투자 유치에 특화되어 있습니다.",
    creditRate: 3,
    enablerScore: 91,
    badgeLevel: "top_rated",
    status: "approved",
    sessionCount: 62,
    rating: 4.8,
    reRequestRate: 72,
    availability: {},
  },
  {
    userId: "e3",
    fullName: "Emily Rodriguez",
    avatarInitial: "ER",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
    university: "HBS",
    degreeType: "MBA '24",
    specialties: ["E-commerce", "Consumer", "Market Research"],
    location: "Boston, MA",
    bio: "Harvard Business School 졸업. Amazon과 Shopify에서의 경험을 바탕으로 한국 브랜드의 미국 D2C 진출을 돕고 있습니다.",
    creditRate: 2,
    enablerScore: 88,
    badgeLevel: "verified",
    status: "approved",
    sessionCount: 45,
    rating: 4.7,
    reRequestRate: 65,
    availability: {},
  },
  {
    userId: "e4",
    fullName: "David Kim",
    avatarInitial: "DK",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
    university: "MIT Sloan",
    degreeType: "MBA '23",
    specialties: ["AI/DeepTech", "Product Strategy", "Tech Partnerships"],
    location: "Cambridge, MA",
    bio: "MIT Sloan에서 기술 전략을 전공. AI 스타트업 2곳을 공동 창업한 경험이 있으며, 딥테크 기업의 미국 시장 진출 컨설팅을 전문으로 합니다.",
    creditRate: 3,
    enablerScore: 92,
    badgeLevel: "top_rated",
    status: "approved",
    sessionCount: 71,
    rating: 4.9,
    reRequestRate: 81,
    availability: {},
  },
  {
    userId: "e5",
    fullName: "Michelle Lee",
    avatarInitial: "ML",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
    university: "Columbia Business",
    degreeType: "MBA '24",
    specialties: ["Healthcare", "Regulatory", "BD"],
    location: "New York, NY",
    bio: "Columbia Business School 졸업. FDA 규제 전문가로서 한국 헬스케어 스타트업의 미국 시장 진입 전략을 수립합니다.",
    creditRate: 2,
    enablerScore: 85,
    badgeLevel: "verified",
    status: "approved",
    sessionCount: 33,
    rating: 4.6,
    reRequestRate: 58,
    availability: {},
  },
  {
    userId: "e6",
    fullName: "Alex Turner",
    avatarInitial: "AT",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    university: "Chicago Booth",
    degreeType: "MBA '23",
    specialties: ["Enterprise Sales", "Channel Strategy", "SaaS"],
    location: "Chicago, IL",
    bio: "Chicago Booth 졸업. Salesforce에서 엔터프라이즈 세일즈를 경험했으며, B2B SaaS 기업의 미국 영업 전략 구축을 전문으로 합니다.",
    creditRate: 2,
    enablerScore: 87,
    badgeLevel: "rising_star",
    status: "approved",
    sessionCount: 28,
    rating: 4.7,
    reRequestRate: 64,
    availability: {},
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    authorId: "s1",
    authorName: "김태호",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    targetId: "e1",
    bookingId: "b1",
    rating: 5,
    comment: "Sarah는 정말 실행력이 뛰어납니다. 미국 파트너사 10곳의 리스트를 직접 만들어주고, 그중 3곳과 미팅까지 잡아주었습니다.",
    createdAt: "2026-03-20",
  },
  {
    id: "r2",
    authorId: "s2",
    authorName: "이수진",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    targetId: "e1",
    bookingId: "b2",
    rating: 5,
    comment: "GTM 전략 컨설팅이 매우 구체적이었습니다. 우리 제품에 맞는 ICP 정의부터 첫 고객 확보 전략까지 체계적으로 잡아주셨어요.",
    createdAt: "2026-03-15",
  },
  {
    id: "r3",
    authorId: "s3",
    authorName: "박준영",
    authorAvatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face",
    targetId: "e2",
    bookingId: "b3",
    rating: 5,
    comment: "IR 자료 리뷰가 매우 도움이 되었습니다. 투자자 관점에서의 피드백이 구체적이고 실용적이었습니다.",
    createdAt: "2026-03-10",
  },
];

export const INSIGHTS: Insight[] = [
  {
    id: "i1",
    authorId: "e1",
    authorName: "Sarah Chen",
    title: "한국 SaaS 기업이 미국 시장에서 흔히 하는 5가지 실수",
    content: "미국 B2B SaaS 시장 진출 시 한국 스타트업들이 자주 범하는 실수와 그 해결 방안을 정리했습니다...",
    tags: ["SaaS", "GTM", "미국진출"],
    publishedAt: "2026-03-18",
  },
  {
    id: "i2",
    authorId: "e2",
    authorName: "James Park",
    title: "2026년 미국 핀테크 투자 트렌드와 한국 스타트업의 기회",
    content: "현재 미국 핀테크 시장의 투자 트렌드를 분석하고, 한국 핀테크 스타트업이 활용할 수 있는 전략을 제시합니다...",
    tags: ["Fintech", "투자", "트렌드"],
    publishedAt: "2026-03-12",
  },
  {
    id: "i3",
    authorId: "e4",
    authorName: "David Kim",
    title: "AI 스타트업의 미국 시장 진출: 기술력만으로는 부족하다",
    content: "뛰어난 AI 기술만으로는 미국 시장에서 성공할 수 없습니다. 기술 파트너십, 규제, GTM 전략의 3가지 축이 필요합니다...",
    tags: ["AI", "DeepTech", "전략"],
    publishedAt: "2026-03-05",
  },
];

export const B2B_STATS = {
  registeredStartups: 24,
  distributedCredits: 480,
  usedCredits: 312,
  completedSessions: 156,
  satisfaction: 4.7,
  utilizationRate: 65,
};

export const STARTUP_CREDITS = [
  { name: "넥스트페이", allocated: 40, used: 32, remaining: 8, status: "active" as const },
  { name: "AIFlow", allocated: 30, used: 28, remaining: 2, status: "low" as const },
  { name: "그린테크", allocated: 25, used: 12, remaining: 13, status: "active" as const },
  { name: "메디링크", allocated: 35, used: 35, remaining: 0, status: "depleted" as const },
  { name: "클라우드잇", allocated: 20, used: 8, remaining: 12, status: "active" as const },
];

export const RECENT_SESSIONS = [
  { startup: "넥스트페이", enabler: "Sarah Chen", date: "2026-03-24", credits: 2, rating: 5 },
  { startup: "AIFlow", enabler: "David Kim", date: "2026-03-23", credits: 3, rating: 5 },
  { startup: "그린테크", enabler: "Emily Rodriguez", date: "2026-03-22", credits: 2, rating: 4 },
  { startup: "넥스트페이", enabler: "James Park", date: "2026-03-21", credits: 3, rating: 5 },
  { startup: "클라우드잇", enabler: "Alex Turner", date: "2026-03-20", credits: 2, rating: 4 },
];

// ─── Dev/Test Mock Data ───────────────────────────────────────────────────────

export const MOCK_CURRENT_USER: User & { startup?: StartupProfile } = {
  id: "u1",
  email: "taeho@nextpay.io",
  fullName: "김태호",
  role: "startup",
  avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
  orgId: "org1",
  isVerified: true,
  createdAt: "2026-01-15",
  startup: {
    userId: "u1",
    companyName: "넥스트페이",
    industry: ["Fintech", "Payments"],
    stage: "Series A",
    usGoal: "미국 결제 시장 진출, B2B 파트너십 구축",
    creditBalance: 8,
    orgId: "org1",
  },
};

export const MOCK_USERS: (User & { startup?: StartupProfile })[] = [
  MOCK_CURRENT_USER,
  {
    id: "e1",
    email: "sarah.chen@stanford.edu",
    fullName: "Sarah Chen",
    role: "enabler",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face",
    isVerified: true,
    createdAt: "2025-09-01",
  },
  {
    id: "admin1",
    email: "admin@kotra.or.kr",
    fullName: "박지원",
    role: "org_admin",
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
    orgId: "org1",
    isVerified: true,
    createdAt: "2025-10-01",
  },
  {
    id: "super1",
    email: "ops@getitdonework.com",
    fullName: "Get It Done 운영팀",
    role: "super_admin",
    isVerified: true,
    createdAt: "2025-08-01",
  },
];

export const ORGANIZATIONS: Organization[] = [
  {
    id: "org1",
    name: "KOTRA",
    slug: "kotra",
    programName: "K-Startup Grand Challenge",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/KOTRA_logo.svg/200px-KOTRA_logo.svg.png",
    inviteCode: "KOTRA2026",
    totalCredits: 200,
  },
  {
    id: "org2",
    name: "창업진흥원",
    slug: "kised",
    programName: "글로벌 스타트업 육성",
    inviteCode: "KISED2026",
    totalCredits: 150,
  },
  {
    id: "org3",
    name: "서울산업진흥원",
    slug: "sba",
    programName: "서울 글로벌 챌린지",
    inviteCode: "SBA2026",
    totalCredits: 100,
  },
  {
    id: "org4",
    name: "중소벤처기업부",
    slug: "mss",
    programName: "글로벌 액셀러레이팅 프로그램",
    inviteCode: "MSS2026",
    totalCredits: 180,
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: "b1",
    startupId: "u1",
    enablerId: "e1",
    type: "standard",
    status: "completed",
    scheduledAt: "2026-03-20T10:00:00Z",
    completedAt: "2026-03-20T11:00:00Z",
    creditsAmount: 2,
    brief: "미국 B2B SaaS 파트너십 전략 및 초기 고객 발굴 방법론 논의",
    meetingUrl: "/meeting/session-b1?name=김태호",
  },
  {
    id: "b2",
    startupId: "u1",
    enablerId: "e2",
    type: "standard",
    status: "completed",
    scheduledAt: "2026-03-21T14:00:00Z",
    completedAt: "2026-03-21T15:30:00Z",
    creditsAmount: 3,
    brief: "Series A IR 자료 리뷰 및 미국 VC 투자 유치 전략 수립",
    meetingUrl: "/meeting/session-b2?name=김태호",
  },
  {
    id: "b3",
    startupId: "u1",
    enablerId: "e4",
    type: "chemistry",
    status: "confirmed",
    scheduledAt: "2026-04-05T09:00:00Z",
    creditsAmount: 1,
    brief: "AI 결제 솔루션 미국 시장 포지셔닝 케미스트리 세션",
    meetingUrl: "/meeting/session-b3?name=김태호",
  },
  {
    id: "b4",
    startupId: "u1",
    enablerId: "e1",
    type: "project",
    status: "pending",
    scheduledAt: "2026-04-10T11:00:00Z",
    creditsAmount: 5,
    brief: "미국 결제 시장 진입 전략 수립 — GTM 로드맵, 파트너 리스트, 첫 고객 확보 플랜 포함 4주 프로젝트",
  },
  {
    id: "b5",
    startupId: "u1",
    enablerId: "e3",
    type: "standard",
    status: "cancelled",
    scheduledAt: "2026-03-15T13:00:00Z",
    cancelledAt: "2026-03-14T09:00:00Z",
    cancelReason: "일정 충돌로 인한 취소",
    creditsAmount: 2,
    brief: "미국 이커머스 채널 전략 및 D2C 진출 가능성 검토",
  },
  {
    id: "b6",
    startupId: "u1",
    enablerId: "e5",
    type: "standard",
    status: "confirmed",
    scheduledAt: "2026-04-08T15:00:00Z",
    creditsAmount: 2,
    brief: "핀테크 규제 환경 분석 — 미국 MSB 라이선스 취득 로드맵 논의",
    meetingUrl: "/meeting/session-b6?name=김태호",
  },
];

export const CREDIT_TRANSACTIONS: CreditTransaction[] = [
  {
    id: "tx1",
    txType: "purchase",
    amount: 200,
    orgId: "org1",
    description: "KOTRA K-Startup Grand Challenge 2026 크레딧 구매",
    balanceAfter: 200,
    createdAt: "2026-01-10",
  },
  {
    id: "tx2",
    txType: "allocate",
    amount: 40,
    orgId: "org1",
    startupId: "u1",
    description: "넥스트페이 크레딧 배정 — KOTRA 프로그램",
    balanceAfter: 40,
    createdAt: "2026-01-15",
  },
  {
    id: "tx3",
    txType: "hold",
    amount: -2,
    startupId: "u1",
    enablerId: "e1",
    bookingId: "b1",
    description: "Sarah Chen 세션 예약 — 크레딧 홀드",
    balanceAfter: 38,
    createdAt: "2026-03-18",
  },
  {
    id: "tx4",
    txType: "confirm",
    amount: -2,
    startupId: "u1",
    enablerId: "e1",
    bookingId: "b1",
    description: "Sarah Chen 세션 완료 — 크레딧 확정 차감",
    balanceAfter: 36,
    createdAt: "2026-03-20",
  },
  {
    id: "tx5",
    txType: "hold",
    amount: -3,
    startupId: "u1",
    enablerId: "e2",
    bookingId: "b2",
    description: "James Park 세션 예약 — 크레딧 홀드",
    balanceAfter: 33,
    createdAt: "2026-03-19",
  },
  {
    id: "tx6",
    txType: "confirm",
    amount: -3,
    startupId: "u1",
    enablerId: "e2",
    bookingId: "b2",
    description: "James Park 세션 완료 — 크레딧 확정 차감",
    balanceAfter: 30,
    createdAt: "2026-03-21",
  },
  {
    id: "tx7",
    txType: "release",
    amount: 2,
    startupId: "u1",
    enablerId: "e3",
    bookingId: "b5",
    description: "Emily Rodriguez 세션 취소 — 홀드 크레딧 반환",
    balanceAfter: 32,
    createdAt: "2026-03-14",
  },
  {
    id: "tx8",
    txType: "allocate",
    amount: 10,
    orgId: "org1",
    startupId: "u1",
    description: "추가 크레딧 지급 — 우수 참여 스타트업 보너스",
    balanceAfter: 42,
    createdAt: "2026-03-25",
  },
];
